services:
  # BE Blue 환경
  be-blue:
    # SHA를 이미지 태그로 사용
    image: registry.ayelcommunity.site/community-be:${BE_IMAGE_TAG}

    # 컨테이너 종료 시 자동 재시작
    restart: unless-stopped

    # Blue 환경 Host Port 8080
    ports:
      - "8080:8080"

    # BE 환경 변수
    env_file:
      - .env

    # 업로드 파일 유지
    volumes:
      - ./uploads:/app/uploads

    # 컨테이너 리소스 제한
    cpus: 1.0
    mem_limit: 768m

    # Blue 환경 네트워크
    networks:
      - blue_net

networks:
  # Blue 환경 전용 네트워크
  blue_net:
    driver: bridge