spring:
  profiles:
    active: prod

  lifecycle:
    timeout-per-shutdown-phase: 30s

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  session:
    store-type: redis

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug

file:
  upload-dir: ./uploads
  allowed-extensions:
    - png
    - jpg
    - jpeg
    - gif

server:
  shutdown: graceful

  tomcat:
    threads:
      max: 20
      min-spare: 5
    max-connections: 500
    accept-count: 50

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET}
      cloudfront-url: ${CLOUDFRONT_URL}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true