spring:
  datasource:
    url: jdbc:mysql://localhost:3306/communityDB?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug

file:
  upload-dir: ./uploads
  allowed-extensions:
    - png
    - jpg
    - jpeg
    - gif

server:
  tomcat:
    threads:
      max: 20              # 최대 스레드 제한 (프리티어 메모리 고갈 방지)
      min-spare: 5         # 최소 대기 스레드
    max-connections: 500   # 최대 동시 연결 제한 (서버 다운 방지용 자원 방어벽)
    accept-count: 50       # 톰캣 대기 큐 제한