# values.yaml

namespace: community-prod

names:
  deployment: community-backend
  service: community-backend-service
  configMap: backend-config
  externalSecret: backend-secret
  secret: backend-secret
  resourceQuota: community-resource-quota
  limitRange: community-limit-range

labels:
  app: community-backend
  tier: backend
  env: prod

replicaCount: 3
revisionHistoryLimit: 3

minReadySeconds: 10
progressDeadlineSeconds: 300
terminationGracePeriodSeconds: 40

strategy:
  maxUnavailable: 0
  maxSurge: 1

topologySpread:
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: ScheduleAnyway

imagePullSecret: registry-secret

image:
  repository: registry.ayelcommunity.site/community-be
  tag: "a2db738568d07b594a99666a0d10624487c9fda7"
  pullPolicy: IfNotPresent

container:
  name: backend-container
  port: 8080

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

lifecycle:
  preStop:
    sleepSeconds: 5

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: community-backend-ingress
  className: nginx
  host: k8s.ayelcommunity.site
  path: /
  pathType: Prefix

config:
  SPRING_PROFILES_ACTIVE: prod
  DB_URL: "jdbc:mysql://10.0.3.237:3306/communityDB?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
  DB_USERNAME: root
  REDIS_HOST: "10.0.3.237"
  REDIS_PORT: "6379"
  S3_BUCKET: ayel-community-storage
  CLOUDFRONT_URL: d1hcjwklzu9rzi.cloudfront.net

externalSecret:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    creationPolicy: Owner

  remoteRef:
    key: community/backend

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"

  limits:
    cpu: "500m"
    memory: "1200Mi"

probes:
  startup:
    path: /actuator/health
    periodSeconds: 5
    failureThreshold: 30
    timeoutSeconds: 2

  readiness:
    path: /actuator/health/readiness
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 2

  liveness:
    path: /actuator/health/liveness
    periodSeconds: 15
    timeoutSeconds: 2
    failureThreshold: 2

resourceQuota:
  pods: "6"
  requestsCpu: "2"
  requestsMemory: "3Gi"
  limitsCpu: "4"
  limitsMemory: "6Gi"

limitRange:
  min:
    cpu: "100m"
    memory: "300Mi"

  max:
    cpu: "1"
    memory: "1200Mi"

  defaultRequest:
    cpu: "250m"
    memory: "400Mi"

  default:
    cpu: "500m"
    memory: "500Mi"