# backend-externalsecret.yaml

apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.names.externalSecret }}
  namespace: {{ .Values.namespace }}

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}

  target:
    name: {{ .Values.names.secret }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}

  data:
    - secretKey: DB_PASSWORD

      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: DB_PASSWORD
