name: BE CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Docker image 빌드
        run: docker build -t community-be:ci .